SELECT *FROM TB_Biz_AccountAuth WHERE Token='7282335bcddf410fa92ae85dc4606cc2'
Go
SELECT *FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TB_Biz_Account'
go
SELECT *FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TB_Biz_Activity'
go
SELECT *FROM TB_Biz_Account WHERE Account=1
go
SELECT *FROM TB_Biz_AccountInvestInfo
go
SELECT *FROM TB_Biz_AccountFinancialInfo
go